# Generated by Django 5.2.7 on 2025-11-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeature',
            name='brands',
            field=models.CharField(choices=[('ASUS', 'ASUS'), ('INTEL', 'INTEL'), ('MSI', 'MSI'), ('GIGABYTE', 'GIGABYTE'), ('EVGA', 'EVGA'), ('ZOTAC', 'ZOTAC'), ('SAPPHIRE', 'SAPPHIRE'), ('XFX', 'XFX'), ('Others', 'Others')], default='Others', max_length=20),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='memory_types',
            field=models.CharField(choices=[('GDDR3', 'GDDR3'), ('GDDR5', 'GDDR5'), ('GDDR6', 'GDDR6'), ('GDDR6X', 'GDDR6X'), ('GDDR7', 'GDDR7'), ('Others', 'Others')], default='GDDR6', max_length=20),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='interface',
            field=models.CharField(choices=[('2.0', '2.0'), ('3.0', '3.0'), ('4.0', '4.0'), ('5.0', '5.0')], default='2.0'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='manufacturer',
            field=models.CharField(choices=[('NVIDIA', 'NVIDIA'), ('AMD', 'AMD'), ('Others', 'Others')], default='OTHER', max_length=20),
        ),
    ]
